name: setup
description: Setup Node and install dependencies

inputs:
  node_version:
    description: Node Version
    required: true
  registry_url:
    description: NPM Registry URL
    required: false
    default: 'https://registry.npmjs.org'
  scope:
    description: NPM Scope
    required: false

runs:
  using: composite
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: ${{ inputs.node_version }}
        registry-url: ${{ inputs.registry_url }}
        scope: ${{ inputs.scope }}

    - name: 🔧 Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies
